### ISSUE TITLE
ساخت یوزر

### ISSUE THREAD

**Issue by mahmoodhabibi333** [Ptechgithub/sing-box#11]
درود بابت پروژه خوب سپاس چطور میشه یوزر اضافه کرد و حجم و روز گزاشت

**Comment by Ptechgithub** [comment]
درود برشما . محدودیت حجم نداره ولی برای اضافه کردن یوزر باید در بخش users از uuid مختلف استفاده کنید. که دستی انجام میشه چون این قابلیت رو بهش اضافه نکردم

**Comment by mahmoodhabibi333** [comment]
> درود برشما . محدودیت حجم نداره ولی برای اضافه کردن یوزر باید در بخش users از uuid مختلف استفاده کنید. که دستی انجام میشه چون این قابلیت رو بهش اضافه نکردم

سپاس
