### ISSUE TITLE
مشکل نصب argo

### ISSUE THREAD

**Issue by meysamrn** [Ptechgithub/sing-box#6]
من تمامی مراحل رو درست پیش می رم ولی متاسفانه گزینه argo نصب نمی شه

**Comment by Ptechgithub** [comment]
مجدد تست کن اگه روی سرور چیز خاسی نداری rebuild کن

**Comment by smf8** [comment]
سلام و وقت بخیر، دلیل خاصی هست که راه اندازی تونل argo فقط داخل config_ip انجام میشه و داخل config_tls انجام نمیشه؟

**Comment by Ptechgithub** [comment]
سلام چون جواب نداد.
