### ISSUE TITLE
عدم نصب با Acme

### ISSUE THREAD

**Issue by mehdivaezi** [Ptechgithub/sing-box#7]
دامنه را میدونم که درست متصل کردم.
حتی با 
https://get.acme.sh | sh
 هم براحتی SSL میگیرم.
 
 ولی متاسفانه با اسکریپ شما خطای زیر داده میشه:
 
 ```
 /dev/fd/63: line 155: dig: command not found
The IP resolved by the current domain name does not match the real IP used by the current VPS
uggestions below :
1. Please make sure that CloudFlare is turned off (DNS only). The same applies to other domain name resolution or CDN website settings.
2. Please check whether the IP set by DNS resolution is the real IP of the VPS
```

**Comment by Ptechgithub** [comment]
سیستم عاملت چیه؟

**Comment by mehdivaezi** [comment]
ubuntu 20.04

**Comment by Ptechgithub** [comment]
الان مجدد تست کنید اگه نشد دستور زیر رو قبلش بزن
apt install dnsutils

**Comment by mehdivaezi** [comment]
درود بهتون.
البته بدون دستور
apt install dnsutils
الان کاملا به درستی کار کرد و فوق العاده ازتون ممنون هستم.
