### ISSUE TITLE
خط ۲۳۵ ارور

### ISSUE THREAD

**Issue by amir385276** [Ptechgithub/sing-box#9]
با سلام و خسته نباشید.
من روی چند تا گوشی تست کردم خط۲۳۵ ارور میده
![Screenshot_۲۰۲۴-۰۲-۲۸-۱۷-۴۳-۱۵-۶۹۴_com.termux.jpg](https://github.com/Ptechgithub/sing-box/assets/43181048/4b36385b-2324-423a-a8f7-d70e037dedd4)

ممنون میشم بررسی بفرمایید.

**Comment by Ptechgithub** [comment]
سلام این اسکریپت وارپ برای سرور هست اگر اسکنر رو میخوای اسکریپت دومی رو اجرا کن روی termux

**Comment by amir385276** [comment]
با درود
دنبال اسکنر نیستم. فقط میخواستم تست کنم کانکشنهای بیشتری داشته باشم.
در ضمن برای ویندوز هفت هم یک راه حل مناسب ارائه بذین ممنون میشم.
میدونم جاش اینجا نیست. 
دستتون درد نکنه و خسته نباشید.
